server.port=8080

# PostgreSQL Connection for Melo-Fine database
spring.datasource.url=jdbc:postgresql://localhost:5432/Melo-Fine
spring.datasource.username=postgres
spring.datasource.password=ranjith123@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Mail (Gmail SMTP configuration)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rannavin72@gmail.com
spring.mail.password=embeaudapjhzresf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Project Info
app.name=Melo-Fine
app.mail.from=rannavin72@gmail.com

# YouTube Data API v3 Key
youtube.api.key=AIzaSyCXFRiVfJ7yQlnXt-LOj7TwMbduxAvRemk
